# Lab 5 ALL

In [6]:
import numpy as np

# Q1 Linear associator network

In [7]:
def purelin(n):
    return n  # Identity function

def linear_associator(W, p):
    a = np.dot(W, p)  # Matrix multiplication between W and p
    a = purelin(a)  # Apply the purelin transfer function
    return a

# Example usage of Q1:
W = np.array([[0.5, 0.8, 0.2], [0.3, 0.4, 0.9]])  # Weight matrix
p = np.array([2, 3, 1])  # Input vector

output = linear_associator(W, p)
print(output)

[3.6 2.7]


# Q2 Hebb learning rule

In [8]:
def hebb_rule(T,p):
    p = np.transpose(p)
    w = np.dot(T,p)
    return w

# Testing Hebb rule

In [9]:
p = [[0.5,0.5], [-0.5,0.5], [0.5,-0.5], [-0.5,-0.5]]
t = [[1,1], [-1, 1]]
w = hebb_rule(t,p)
print (w)


[[ 1.  0.  0. -1.]
 [ 0.  1. -1.  0.]]


# Q3 Function that checks if two vectors are orthogonal

In [10]:
def check_orthogonal(a,b):
    b = np.transpose(b)
    c = np.dot(a,b)
    return c

# Testing the function

In [11]:
p1 = [0.5,-0.5,0.5,-0.5]
p2 = [0.5,0.5,-0.5,-0.5]
c = check_orthogonal(p1,p2)
print(c)

0.0


# "check_orthogonal” by passing the following vectors to it

In [12]:
p1 = [1,-1,-1] 
p2 = [1,1,-1 ] 
c = check_orthogonal(p1,p2)

print("c is = ", c)

c is =  1


# Q4 a function that checks if a vector is of unit length

In [13]:
def check_unitlength(a):
    a_transpose = np.transpose(a)
    c = np.dot(a,a_transpose)
    return c

# Test the function “check_unitlength” 

In [14]:
p = [0.5,-0.5,0.5,-0.5]
c = check_unitlength(p)
print(c)

1.0


# Test the function “check_unitlength” by passing the following vector to it.  

{𝒑𝟏 =[1 , -1 ,-1]}


In [15]:
p1 = [1,-1,-1] 
c = check_unitlength(p1)
print(c)

3


# Q5

In [19]:
def normalizevec(a):
    a = np.array(a)
    norm = np.linalg.norm(a)
    c = a / norm
    return c
p1 = [1, -1, -1]
print(normalizevec(p1))

[ 0.57735027 -0.57735027 -0.57735027]


# Q6

In [20]:
p1 = [1,-1,-1]
p2 = [1,1,-1]

check_orthogonal(p1,p2)


1

# Q=2   R=3    T=1    P=2  

In [21]:
p1 = [1,-1,-1]
print(check_unitlength(p1))


3


In [22]:
p2 = [1,-1,-1]
print(check_unitlength(p2))


3


In [23]:
p1 = [1,-1,-1]
print(check_unitlength(p1))
print(normalizevec(p1))

3
[ 0.57735027 -0.57735027 -0.57735027]


In [24]:
p2 = [1,-1,-1]
print(check_unitlength(p2))
print(normalizevec(p2))

3
[ 0.57735027 -0.57735027 -0.57735027]


In [26]:
normalized_p1 = [0.57735027 , -0.57735027 , -0.57735027]
normalized_p2 = [0.57735027 , 0.57735027 , -0.57735027]
t = [-1,1]
normalized_p = np.vstack((normalized_p1,normalized_p2)).T
print(hebb_rule(t,normalized_p))

[0.         1.15470054 0.        ]
